packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@orpc/server": ^1.9.0
  "@orpc/openapi": ^1.9.0
  "@orpc/zod": ^1.9.0
  better-auth: ^1.3.13
  ai: ^5.0.49
  "@ai-sdk/google": ^2.0.13
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  tsdown: ^0.15.5
  "@orpc/client": ^1.9.0
  "@polar-sh/better-auth": ^1.1.3
  drizzle-orm: ^0.44.2
