packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^2.0.13
  '@orpc/client': ^1.9.0
  '@orpc/openapi': ^1.9.0
  '@orpc/server': ^1.9.0
  '@orpc/zod': ^1.9.0
  '@polar-sh/better-auth': ^1.1.11
  ai: ^5.0.77
  better-auth: ^1.3.29
  dotenv: ^17.2.2
  drizzle-orm: ^0.44.2
  hono: ^4.8.2
  tsdown: ^0.15.5
  typescript: ^5.8.2
  zod: ^4.1.11
