# name: E2E-testing
# on: [push]
# jobs:
#   e2e:
#     env:
#       NODE_ENV: test
#       NEXTAUTH_SECRET: supersecret
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         node: ['18.x']
#         os: [ubuntu-latest]
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - uses: onichandame/node-test-action@master

#       - name: Use Node ${{ matrix.node }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node }}
#           # cache: 'pnpm' # You can active this cache when your repo has a lockfile

#       - name: Install deps (with cache)
#         run: yarn install

#       - name: Install playwright
#         run: yarn playwright install chromium

#       - name: Next.js cache
#         uses: actions/cache@v3
#         with:
#           path: ${{ github.workspace }}/.next/cache
#           key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

#       - name: Build and test
#         run: yarn build-sqlite && yarn test-start && yarn test-dev

#       - name: Upload test results
#         if: ${{ always() }}
#         uses: actions/upload-artifact@v2
#         with:
#           name: test results
#           path: |
#             playwright/test-results

name: E2E-testing
on: [push]
jobs:
  e2e:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Install playwright
        run: yarn playwright install chromium

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      # - name: Test the app
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test # will run `yarn test` command

      - name: Build and test
        run: yarn build && yarn test-start

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            playwright/test-results
